version: '3.7'
services:
  vue:
    container_name: portfolio-vue
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/html/app
      - /var/www/html/app/node_modules